### ISSUE TITLE
extra gridlabd.exe

### ISSUE THREAD

**Issue by jcfuller1** [gridlab-d/gridlab-d#1028]
(reported by @ftuffner)
During the build/install process, an artifact gridlabd.exe is generated in the main code folder.  It appears to be linked to a "temporary wrapper generated for libtool".

Two problems:
1) The script should clean up after itself and remove this file.

2) In debug mode (-D_DEBUG), when running GLD from the command line, it sees this gridlabd.exe first (rather than seeing the PATH gridlabd.exe or the same folder gridlabd.exe).  This is interesting, since that code path is in none of the paths.  When running with Eclipse, this does not occur.  In 'non-debug', this does not occur.  I'm worried that a path is being hard-coded into a DLL somewhere.

**Comment by nikhilgupta10** [comment]
make install builds the project in the main directory and copies the .exe to the $<PATH> specified in ./configure. @ntenney thinks it is an odd step to clean the main directory from "make install".

Instead, doing a "make clean" after "make install" should clean the current working directory.

**Comment by ftuffner** [comment]
It is definitely cleaned up by the "make clean" command, so that seems to indicate the make script is at least aware of its existence.  Does this mean there's no way to get that "temporary exe" deleted as part of the make process?

**Comment by nikhilgupta10** [comment]
One thing to be careful about "make clean" - since it deletes everything in the current project this might be little painful for a developer.

Also, the same behavior can be observed in Unix systems (since make install always installs in the current project directory). But we are facing trouble in Windows machines because "MinGW/msys" defaults "." at the very beginning of the $PATH. 

So, instead of appending the install folder to the $PATH, if we can prepend it, then the system would see the install folder before "." and that should fix the problem. 

This will be updated once the fix is implemented.

**Comment by dchassin** [comment]
Could the presence of this file explain the persistent problem I've had getting debugging to work using Eclipse in Windows?  I've never been able to solve this problem and I simply stopped developing on Windows altogether because of it.

**Comment by afisher1** [comment]
So the existence of this file through make is normal. The problem is that in msys by default "." is present in the path. So you can either delete the file or prepend the location to the install location to the path.

Sent from my iPhone

On Apr 6, 2017, at 7:16 AM, David P. Chassin <notifications@github.com<mailto:notifications@github.com>> wrote:


Could the presence of this file explain the persistent problem I've had getting debugging to work using Eclipse in Windows? I've never been able to solve this problem and I simply stopped developing on Windows altogether because of it.

**Comment by nikhilgupta10** [comment]
As detailed in above comments, two ways to handle this is:
1. make clean after make install
2. rm ./gridlabd.exe
