### ISSUE TITLE
Add epoch-time as recorder timestamp option

### ISSUE THREAD

**Issue by trevorhardy** [gridlab-d/gridlab-d#1029]
Adding parameter on recorders that allows the timestamp to appear as epoch time.

**Comment by dchassin** [comment]
That is an excellent suggestion and would probably remedy a number of problems with data import/export, especially to mysql.  You may want to support other common serialization formats, like that used by Excel.  

One thought:  There is a suggestion somewhere else that we extend the unit formatting system to support what is already supported by the server, i.e., allow the unit system to be used for non-real/complex valued properties.  That way we could ask for a property to be formatted on the fly instead of using a global variable.  The property export would then be something "my_date[EPOCH]" or "my_date[ISO]" regardless of what the global date format is set to.

**Comment by trevorhardy** [comment]
Functionality already existed for recorders and multi_recorders; setting "format" to a non-zero value changed the output to a TIMESTAMP (epoch time) value rather than a traditional, human-readable string.

Such functionality was explicitly excluded from the group recorders; justice has prevailed and I have added it back in with the same syntax as in recorders and multi_recorders.

**Comment by trevorhardy** [comment]
For reasons that are not clear to me, the "format" property in recorders and multi-recorders was declared in those objects structs but not tied into the GridLAB-D property system. To enable this functionality for all of the recorder flavors, I've made that connection. Now setting "format" to "1" in all of these objects will set the timestamp to epoch time.

Added an autotest that includes a recorder, multi_recorder, and group_recorder producing output files with epoch timestamps. Since we don't have an assert object that can check these files easily, the autotest will only fail if later development somehow invalidates the "format" property.

**Comment by trevorhardy** [comment]
Merged back into develop.

**Comment by dchassin** [comment]
Using "format" as the name seems unclear because we're not formatting the property, but date field.  Maybe naming it "date_format" would be better.  Also, having it be an enum to allow multiple formats may be preferred because "format" does not imply a boolean choice (e.g., use_epoch_value).  The enum values could be {USE_DEFAULT=0, USE_EPOCH=1, USE_ISO=2, USE_US=3, USE_EU=4} for example.
