### ISSUE TITLE
Deltamode Diesel_DG model gives different results between 32 bit and 64 bit versions of the code

### ISSUE THREAD

**Issue by afisher1** [gridlab-d/gridlab-d#1041]
There are two failing autotests for diesel_dg in 32 bit windows. The tests are test_deltamode_diesel_dg_assert.glm, test_deltamode_diesel_dg_pctests.glm. typically failures in 32 bit are due to differences in numerical rounding. To help mitigate this it is always best to use doubles for all floating point numbers as a double is a 64 bit type and should be represented the same under both architectures.

**Comment by ftuffner** [comment]
Tried a first attempt at seeing if a macro was being cast funny.  PI appears to be the only "macro value" in diesel_dg -- published it and checked the values between x86 and x64 GridLAB-D -- appear the same out to 20 digits, so that doesn't appear to be the case.  Going to look into trigonometric/transcendental functions next, since they have had some odd behavior in the past.

**Comment by ftuffner** [comment]
Turned out to be a casting/rounding issue with governor delay lengths.  Committed as part of 8f355aa9..2ed13069.  All autotests appear to pass for x86 and x64 builds under Windows now.

**Comment by afisher1** [comment]
I've confirmed on windows and linux. Closing issue.
