### ISSUE TITLE
Wind speed unit conversion may be wrong

### ISSUE THREAD

**Issue by dchassin** [gridlab-d/gridlab-d#1155]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [X] I have not found an open issue describing the same problem.
- [X] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

## Please describe what was the cause of the issue?

There may be a problem with wind speed.  The climate object publishes wind speed in units of m/s (see https://github.com/gridlab-d/gridlab-d/blob/c9da53c5eaf4038311d61364a428e95531f1becd/climate/climate.cpp#L547), and converts the TMY values from m/s to mph (https://github.com/gridlab-d/gridlab-d/blob/c9da53c5eaf4038311d61364a428e95531f1becd/climate/climate.cpp#L884). 

## Please provide the steps to reproduce.

Visual inspection of the code in climate/climate.cpp.

## Please provide the exact error/warnining/failure message printed on the console.

N/A.

## If possible, please provide any screenshots and other supporting information.

N/A

**Comment by laurmarinovici** [comment]
This issue seems to still exist. I was just about to report it.

I am using feature/1173 and just noticed this discrepancy as I was comparing some data between GridLAB-D wind speed from TMY3 file, and wind speed manually fed into GridLAB-D through FNCS (which was previously extracted from TMY3). See attached. (no FNCS means using TMY3 files, with FNCS means using a DAT file with data extracted from TMY3 previously)

![wind_speed](https://user-images.githubusercontent.com/6537831/77484473-dc5a4d80-6de7-11ea-9a27-7cbf5467ef5c.png)

Once the external values were converted to miles per hour, everything matched.

![wind_speed](https://user-images.githubusercontent.com/6537831/77484539-0875ce80-6de8-11ea-9b4c-676da6d3a87b.png)

**Comment by d3j331** [comment]
It has been tested in TESP v1.1.5. in example\capabilities\weatherAgent.  Using Navajo [e03b3337:develop:Mod] 

![image](https://user-images.githubusercontent.com/46505877/188756334-f144a5cf-29c6-463d-bfb6-e9f41a2090cf.png)
