### ISSUE TITLE
Measured real/reactive energy in meter/triplex_meter yield incorrect values

### ISSUE THREAD

**Issue by dchassin** [gridlab-d/gridlab-d#1194]
## Please describe what was the cause of the issue?

The method of calculating measured real/reactive energy in `meter` and `triplex_meter` `postsync()` results in the measurement being taken only on the first `postsync()` call.  Subsequent updates to measured real/reactive power are ignored and the original result from the first iteration is kept.  As a result, the measured energy values may be erroneous when more than one iteration is performed.

In addition, if non-zero values of measured power are used to create the meter or triplex_meter object, then the simulation integrates these values from the start of the epoch. This results in erroneous energy measurements right from the outset.

## Please provide the steps to reproduce.

This isn't something one reproduces so much as deduces from inspection of the code in `meter::postsync()` and `triplex_meter::post sync()`.  

## Please provide the exact error/warning/failure message printed on the console.

There is no outward indication of a problem. Presumably detecting the problem requires a side-by-side comparison of the output of a recorder of the meter that sample energy with the output a recorder that samples power at -1 intervals.

## If possible, please provide any screenshots and other supporting information.

None available.

**Comment by ftuffner** [comment]
@dchassin I lost this in the mix for a few months (obviously).

For the first problem, what is implemented doesn't quite behave as it is described above.  One could argue the energy metering is actually a timestep behind, depending on your perspective.  It updates the energy calculation using the prior value of calculated power (`measured_power_real` and `measured_power_reactive` are updated after the energy calculation).  This would be the final power of the prior timestep/iteration cycle, so it should capture any reiterations.  The idea was that since it technically had the power from t0 to t1, that is the value to integrate over for energy.  That logic could potentially be revisited, but I'm not sure exactly how we'd want it to behave.

For the second issue, that is a problem.  It should be easy to fix via an `init()` addition.  Maybe a warning can be tossed in there to make sure the users know we just protected them from themselves.

**Comment by dchassin** [comment]
@ftuffner, thanks for looking at this.

1) I see the lag issue now.  That's too bad, and it seems hard to fix. I tried a quick fix myself, and I just made things worse.

2) I think a warning would be ok, but that would he a showstopper in situations where we want to pick up where we left off after a data dump (which is where we encountered all this).

**Comment by ftuffner** [comment]
@dchassin I'll add the appropriate `init` items and toss a warning in there - it should be pretty easy.

For picking up where a data dump left off, couldn't you just put the prior values of accumulator into something like `measured_real_energy`?  It doesn't look like it is overwritten ever, so if you initialized it with a prior value, it should just start accumulating on top of it.

**Comment by ftuffner** [comment]
Warnings merged in.  Closing this for now.
