### ISSUE TITLE
feature/1173 showing erroneous behavior on Windows

### ISSUE THREAD

**Issue by esilksel** [gridlab-d/gridlab-d#1222]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [x] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [x] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
Building with the suggested settings on Windows and connect a three-phase system to a house.

## Please provide the steps to reproduce.

1. Clone repo into MSYS2 environment
2. Checkout feature/1173
3. Run `autoreconf -if`
4. Run `./configure --build=x86_64-mingw32 --with-xerces=/mingw64 --enable-silent-rules 'CFLAGS=-O0 -w' 'CXXFLAGS=-O0 -w' 'LDFLAGS=-O0 -w -L/mingw64/bin'`
5. Run `make` then `make install`
6. Run both `gridlabd testbed_triplex.glm` and `gridlabd testbed_3ph.glm`
7. Compare results

## Please provide the exact error/warnining/failure message printed on the console.
triplex_current2.csv:
```
# timestamp,measured_current_A,measured_current_B,measured_current_C
1999-12-31 16:00:00 PST,+1.25956-0.024241j,+0+0j,+0+0j
1999-12-31 16:00:01 PST,+1.25956-0.024241j,+0+0j,+0+0j
# end of tape
```
3ph_current2.csv:
```
# timestamp,measured_current_A,measured_current_B,measured_current_C
1999-12-31 16:00:00 PST,+2.75985e-014+3.26164e-014j,-1.08895e-013-9.07462e-015j,+9.07462e-015-1.08895e-013j
1999-12-31 16:00:01 PST,+2.75985e-014+3.26164e-014j,-7.94029e-014-3.40298e-014j,+1.08895e-013+9.07462e-015j
```
On an Ubuntu 18.04 machine, triplex_current2.csv matches while 3ph_current2.csv produces:
```
# timestamp,measured_current_A,measured_current_B,measured_current_C
2000-01-01 00:00:00 UTC,+0.416215-0.00337286j,-0.211031-0.358828j,-0.205176+0.36222j
2000-01-01 00:00:01 UTC,+0.416215-0.00337288j,-0.211031-0.358828j,-0.205176+0.36222j
# end of tape
```
This version was build with the following configuration args:
```
./configure --prefix=/usr/local/ --enable-silent-rules "CFLAGS=-O0 -w" "CXXFLAGS=-O0 --std=c++14" "LDFLAGS=-O0 -w"
```

## If possible, please provide any screenshots and other supporting information.
In an attempt to determine if the nature of the build might be to blame, the MSYS2 version was re-compiled with `--std=c++14`  as a `CXXFLAG`, but this caused a compilation failure.

Running `gridlabd --version`, Windows version reports:
```
GridLAB-D 4.1.0-18275 (Lugo [8c2aa145:feature/1173]) 64-bit WINDOWS RELEASE
```
Linux:
```
GridLAB-D 4.1.0-18275 (Lugo [8c2aa145:feature/1173]) 64-bit LINUX RELEASE
```

Attached are the glms, the requisite `*.tmy3` file, and the results of the sims. Let me know if anything appears erroneous.
[linux.zip](https://github.com/gridlab-d/gridlab-d/files/4124881/linux.zip)
[windows_files.zip](https://github.com/gridlab-d/gridlab-d/files/4124882/windows_files.zip)

-------------------------------------------------------------------------------------------------------------

**Comment by esilksel** [comment]
@Ross-selinc Feel free to chime in/work with whoever is assigned on this issue.

**Comment by ftuffner** [comment]
@esilksel The c++14 flag issue is known (actually fixed in another issue and awaiting a pull request merge).

In regards to the issue, I'm unable to duplicate it.  Aside from an odd timezone issue (default for the machine, and since the GLM doesn't specify one), my Linux and Windows outputs are identical.  However, it may be a difference in "MSYS2 build components".

Can you post your version of GCC (`gcc --version`), autoreconf (`autoreconf --version`), and MSYS2 (`pacman -Q msys2-runtime`)?

You can also try just updating MSYS2 (`pacman -Syuu`), then try to recompile it (I'd recommend either cloning a new repo, or run all the commands again, with a `make clean` after the `./configure` step).

I'm hoping it is just a GCC version issue, but we'll see if that yields anything.

**Comment by esilksel** [comment]
Sure, I'm hoping its just something we're doing wrong :)
Outputs (snipping extraneous info):
```
gcc --version
gcc.exe (Rev2, Built by MSYS2 project) 9.2.0
autoreconf --version
autoreconf (GNU Autoconf) 2.69
pacman -Q msys2-runtime
msys2-runtime 3.0.7-6
```
Ran `pacman -Syuu` and it said I was up to date.

For completeness, on Linux (Ubuntu 18.04):
```
gcc --version
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
autoreconf (GNU Autoconf) 2.69
```
Perhaps the newer version of gcc on MSSY2 is causing a regression?

I reran the files, making a point to copy the same files to both locations, just for a sanity check. Thought my results were agreeing suddenly, remembered I had put the `develop` build on my Linux machine, uninstalling and installing `feature/1173` reproduced the issue for me. Both are on commit `8c2aa145`.

**Comment by ftuffner** [comment]
@esilksel I'd like to blame MSYS2, but your versions are identical to mine and my outputs are match between OSes.

Just to clarify, the `develop` result produced the "near-zero" or similar values, but swapping to `feature/1173` gave you the "proper values" on Linux? (just making sure I understand the situation as a non-issue)

As another venue to explore, how are you running the file in Windows?  Are you copying the executable into the same folder and just running it there, running a command prompt with the environment set, or trying to run it within MSYS2?  Depending on how you're running it, we may need to check a couple environmental variables (to make sure things aren't getting crossed somewhere).

As a point of reference, when I run files, I'm usually using a new command window or console terminal, with the environment set in it (mostly because I run so many versions of GridLAB-D).  If you're doing it a different way, I can try to replicate that approach on my side.

**Comment by esilksel** [comment]
I am building within MSYS2, `make install`-ing it, and running it within MSYS2. If it is preferred to put it somewhere else, I can give that a shot.

Contents of 3ph_current2.csv on MSYS2 is:
```
# file...... 3ph_current2.csv
# date...... Wed Jan 29 15:47:00 2020
# user...... ericsilk
# host...... (null)
# target.... meter 13
# trigger... (none)
# interval.. 1
# limit..... 1
# timestamp,measured_current_A,measured_current_B,measured_current_C
1999-12-31 16:00:00 PST,+2.75985e-014+3.26164e-014j,-1.08895e-013-9.07462e-015j,+9.07462e-015-1.08895e-013j
1999-12-31 16:00:01 PST,+2.75985e-014+3.26164e-014j,-7.94029e-014-3.40298e-014j,+1.08895e-013+9.07462e-015j
# end of tape
```

Contents of 3ph_current2.csv on Linux:
```
# file...... 3ph_current2.csv
# date...... Wed Jan 29 15:54:03 2020
# user...... ericsilk
# host...... (null)
# target.... meter 13
# trigger... (none)
# interval.. 1
# limit..... 1
# timestamp,measured_current_A,measured_current_B,measured_current_C
2000-01-01 00:00:00 UTC,+0.416215-0.00337286j,-0.211031-0.358828j,-0.205176+0.36222j
2000-01-01 00:00:01 UTC,+0.416215-0.00337288j,-0.211031-0.358828j,-0.205176+0.36222j
# end of tape
```
Your question about environment got me thinking, running `printenv` showed GLPATH being set to the old install (via the Windows installer) rather than anything within the MSYS2 environment. So, upon uninstalling the Windows version, it now refuses to run within MSYS2, leading me to believe it may have been relying on the wrong stuff even though `which gridlabd` reports `/usr/bin/gridlabd`.

What's the suggested method to build via MSYS2 and install outside that environment so I can have `GLPATH` set correctly?

**Comment by ftuffner** [comment]
@esilksel Having it "cross-linking" to old or different installs can certainly cause problems.  There is a bash script in the `<install_folder/bin>` directory which can set the various variables.  I usually just set them manually, but that's again because I have too many versions of GridLAB-D.

Note that for all of the paths I put in here, you may need to tweak them a bit.  Based on the `configure` command above, I'm assuming everything is based in `/usr/local`, so I used that as the parent directory.  Based on your last entry, you may need to make something like `/usr/local/bin` just be `/usr/bin`.

If you want to explicitly use the bash script mentioned, it would probably be something like:

`/usr/local/bin/gridlabd.sh testbed_triplex.glm`

To run GridLAB-D, you basically need to point the `PATH` variable to the bin folder, and set `GLPATH` to the `lib/gridlabd`, `share/gridlabd`, and `include/gridlabd` folders.

Here's an example, again assuming `/usr/local` is the parent folder:

`export PATH=$PATH:/usr/local/bin
export GLPATH=/usr/local/lib/gridlabd:/usr/local/share/gridlabd:/usr/local/include/gridlabd`

For reference, I did just try running it directly in MSYS2 (both with the script, and manually setting the environment) and still get the same (matching) outputs I did before, so it "theoretically" isn't that.

Regarding MSYS2, if you know where it installed, you can also run it in a normal WIndows command prompt (or PowerShell, if you prefer that method).  I'm not sure where `/usr/local` is in the Windows file representation of MSYS2 - I typically just redirect it to a folder in the repository I can easy find.  If you know where it is located (I'll use `C:\GLD_Compiled` here), you can do a similar version of the MSYS2/Linux above:

`set PATH=%PATH%;C:\GLD_Compiled\bin
set GLPATH=C:\GLD_Compiled\lib\gridlabd;C:\GLD_Compiled\share\gridlabd;C:\GLD_Compiled\include\gridlabd`

A final note on this, for the various `export` and `set` commands above, these typically are only local environment setups for that particular terminal/command window.  Once you exit, they are lost and the old defaults come back.  If you wanted them to persist, you'd need something that actually puts them into the machine/persistent environment (which I avoid, for the multiple versions point mentioned previously).

**Comment by esilksel** [comment]
Yep, confirmed this was just an artifact of dual installs. Whew. Going to point relevant parties to this information. Thanks for the help!
