### ISSUE TITLE
Module 'connection' load failed, even if the dll exists

### ISSUE THREAD

**Issue by Seragonia** [gridlab-d/gridlab-d#1227]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [X] I have not found an open issue describing the same problem.
- [x] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
I would like to run Gridlab-D on Windows 10, with Helics support. I use the DistributionSim_B2_G_1.glm model. When I first launched GridLab-D from Helics Runner, GridLab-D tried to load the connection.dll module, but failed. I am able to reproduce the error just by launching gridlab from a CLI. So the error doesn't seem to be related to helics.

This problem differs from issue #1171, since the dll file does exist in my _C:\Program Files\GridLAB-D\lib_ folder. I also tried to reinstall gridlab-d (at the root directory), without success.

Also, all GridLab-D environment variables are set:
(PATH)
```
C:\Program Files\GridLAB-D\lib
C:\Program Files\GridLAB-D\bin
```

(GRIDLABD)
```
C:\Program Files\GridLAB-D
```

(GLPATH)
```
C:\Program Files\GridLAB-D\bin
C:\Program Files\GridLAB-D\etc
C:\Program Files\GridLAB-D\lib
C:\Program Files\GridLAB-D\samples
C:\Program Files\GridLAB-D\rt
C:\Program Files\GridLAB-D\tmy
```

## Please provide the steps to reproduce.
**GridLab-D version**: gridlabd-rc4.2-x64 (from the Windows Installer), but also 4.1 and 4.1-RC1.
Install GridLab-D from the Windows installer executable.

## Please provide the exact error/warning/failure message printed on the console.

Command that trigger the error:
```
$ gridlabd -L connection
ERROR    [INIT] : gldcore/module.c(422): module 'connection' load failed - "C:\Program Files\GridLAB-D\lib\connection.dll": The specified module could not be found.
ERROR    [INIT] : Module connection load failed
```

Full logs:
```
... gldcore/module.c(290): module 'connection' not yet loaded
   ... creating gridlabd signal handler 15 for process 16204
   ... gldcore/module.c(370): module 'connection' memory allocated
   ... full path to library 'connection' is 'C:\Program Files\GridLAB-D\lib\connection.dll'
ERROR    [INIT] : gldcore/module.c(422): module 'connection' load failed - "C:\Program Files\GridLAB-D\lib\connection.dll": The specified module could not be found.
ERROR    [INIT] : Module connection load failed
   ... load time: 0 sec
   ... starting up batch environment
   ... initializing objects...
   ... creating index 0
   ... creating index 1
   ... creating index 2
   ... shuffled -10 lists in index 0
   ... shuffled -10 lists in index 1
   ... shuffled -10 lists in index 2
   ... shutdown complete
   ... elapsed runtime 0 seconds
   ... exit code 0
```

```
$ whereis connection.dll
connection: /c/Program Files/GridLAB-D/lib/connection.dll
```

## If possible, please provide any screenshots and other supporting information.

Here, we can see that the market module is correctly loaded (via Cmder):
![error](https://user-images.githubusercontent.com/30507286/74553162-befead80-4f24-11ea-8aba-1e1cb0255bf4.png)

-------------------------------------------------------------------------------------------------------------

**Comment by ftuffner** [comment]
@Seragonia The HELICS support may not be being directly compiled in/enabled as part of the installers.  We'll need to check on that.  In the mean time, HELICS support via compiling the source code and explicitly linking it in does work.

**Comment by ftuffner** [comment]
@afisher1 I know we explicitly tested precompiled-HELICS library support with 4.2, but I don't know if that was ever part of the release/installer or not.  Any insights?

**Comment by Seragonia** [comment]
> 
> 
> @Seragonia The HELICS support may not be being directly compiled in/enabled as part of the installers. We'll need to check on that. In the mean time, HELICS support via compiling the source code and explicitly linking it in does work.

Thank you very much for your answers, I will try to compile the project from my side.

Also, when I list the features present in connection.dll, I can see helics-related functions:
![error](https://user-images.githubusercontent.com/30507286/74555364-90cf9c80-4f29-11ea-8901-3ab9a687dc0e.png)

If the installer does not come with support for Helics, then perhaps these functions require the support to be active, otherwise it is not possible to use the connection.dll?

**Comment by ftuffner** [comment]
@Seragonia This may bean "unfortunate consequence" of some sloppy set up on our part.  For most of the more optional modules (e.g., MySQL and MATLAB), we have them `#IFDEF`ed out of the code, so they wouldn't show up as an exposed function in the DLL.  It looks like we haven't done that for connection, likely because it is a few items.

Basically, a base form of the library gets built as part of the GridLAB-D compiling process.  However, if it doesn't have HELICS linked in at the time, the functions are basically empty/non-functional.  So in the case of the connection.dll you have, I suspect those are effectively empty functions.  So we'd basically need to build a copy of the connection module with HELICS properly linked in, ideally a version we distribute with GridLAB-D (or indicate how to get).

So the short answer is those functions do require HELICS support to be active, but I'm fairly certain it is a compile-time action, so just getting HELICS working on your computer won't make them suddenly start behaving (especially for your initial error messages).

We'll need to wait for @afisher1 to chime in to verify that -- he's been more directly involved in the GridLAB-D installer and HELICS support, and may indicate if this is truly the case, or where my assessment is incorrect.

**Comment by ftuffner** [comment]
No updates in a while and for prior version of GLD.  Release v4.3 includes HELICS by default.  Self-compiled may still have this issue, but may get resolved as part of cmake-based update.
