### ISSUE TITLE
Probable erroneous tautology in powerflow/load.cpp

### ISSUE THREAD

**Issue by dchassin** [gridlab-d/gridlab-d#1266]
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [X] I have not found an open issue describing the same problem.
- [X] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?

There is a tautology that is very likely erroneous in `powerflow/load.cpp` at https://github.com/gridlab-d/gridlab-d/blob/46541cb8babdd34e371c42467c3830f03f73b96c/powerflow/load.cpp#L1861.

## Please provide the steps to reproduce.

Unable to provide an example of how to detect whether the code is erroneous.

## Please provide the exact error/warnining/failure message printed on the console.

Some compilers issue the following warning during build phase:

~~~
powerflow/load.cpp:1861:61: warning: bitwise comparison always evaluates to false [-Wtautological-bitwise-compare]
                                                if (((NR_busdata[node_reference_value].phases & 0x02) == 0x01) 
~~~

## If possible, please provide any screenshots and other supporting information.

NA

-------------------------------------------------------------------------------------------------------------

**Comment by ftuffner** [comment]
Oh yes.  Definitely erroneous.  Very clearly an over-zealous copy-paste.  So much so that I did it three times in the same file!

This issue basically only emerges with in-rush/impedance conversions, and only if the load was only phase B.  As such, it's no wonder we never directly encountered it.  Good thing the compilers notice these things.

Fixed and pushed directly to develop, since it is a small typo.
