### ISSUE TITLE
#782 recorder/collectors does not use .mag or .ang,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#782]
Class and documentation states that recorders/collectors can use extensions: real, imag, mag, ang, arg for complex numbers. However, it appears that only real and imag are supported.  

See forum post:  

http://sourceforge.net/p/gridlab-d/discussion/842562/thread/db155ace/?limit=25#6857  

,

**Comment by trevorhardy** [comment]
RADICS needs this and I was going to implement this myself but under Jeff Daily's instruction it became clear that it was beyond my not-so-speedy coding skills. Jeff has agreed to implement this and I'll do the testing.

**Comment by dchassin** [comment]
Whoever ends up doing this should be aware that there is a core API for handling part in general now, but the module doesn't use it.  The gl_get... functions need to support parts and the module needs to use that function, instead of doing it internally as the legacy code does now.

The core parts API isn't fully function, so it can't yet get parts to structures. There needs to be some extra code added in the core to enable that capability properly.  As a result, enduse, loadshape, arrays, and such don't work properly.

Also, as far as I know the parts support of the C++ API isn't working correctly either, which is why the mysql module doesn't support complex parts well either.

**Comment by trevorhardy** [comment]
I've verified that the "property.part" for collectors do appear to support the following ".parts":
- .real
- .img
- .mag
- .ang (degrees)
- .arg (radians)

This is consistent with the documentation at [http://gridlab-d.shoutwiki.com/wiki/Collector](url).

**Comment by trevorhardy** [comment]
Feature added to both recorder and multi-recorder. No auto-test added as auto-tests are unable to examine output files to compare against known values.
