### ISSUE TITLE
#920 premature deferred initialization failure,


### ISSUE THREAD

**Issue by nikhilgupta10** [gridlab-d/gridlab-d#920]
init_by_deferral_retry() causes init_by_deferral() to stop trying deferred initialization too early and then free memory that has already been freed.  A weak fix is implemented in r5014 in ticket/910 but it's possible that fix will cause a memory leak.,

**Comment by ftuffner** [comment]
As a side note in here, issue #869 may be relevant here too.

**Comment by ftuffner** [comment]
It was a double-freed pointer, basically due to an improper reassignment (hence why it looked like it was getting trashed, but still existed).  Fixed and added some "malloc checks and free NULLs" to make the code a little more proper.  Also added autotest to explicitly check for this type of issue.  Merged into /develop and release/RC4.0 (since this could be a fairly major item).
